### PR TITLE
Update deps.ts

### PR DESCRIPTION
**Pull request by disjukr**

### CODE REVIEW

**Comment by eliassjogreen** [comment]
LGTM

**Comment by disjukr** [comment]
@eliassjogreen Could you please release a new version? Needed to run on deno 1.14.0.

**Comment by eliassjogreen** [comment]
done!

**Comment by disjukr** [comment]
great. thank you!

**Comment by afiiijooon** [comment]
> _No description provided._

Fly to the moon

**Comment by afiiijooon** [comment]
Build a bright future, dream wealth for yourself and the future

**Comment by afiiijooon** [comment]
Stop trying to succeed, sign for you again

**Pull request merged**
